### ISSUE TITLE
y_pred_test is not defined

### ISSUE THREAD

**Issue by waleedgeo** [omarseleem92/flood_susceptibility_mapping#3]
Dear Omar,

You used the variable "y_pred_test" in your accuracy report, which is not defined previously and gives an error.

![image](https://user-images.githubusercontent.com/72144434/218003189-c0528c38-7951-4806-85dc-fcf52370386d.png)

**Comment by omarseleem92** [comment]
Dear Waleed, 

Thank you for this remark. I changed it to y_pred. 

Best regards. 
Omar
